#!/bin/bash

JENKINS_DIR="/var/lib/jenkins"
JENKINS_CHKDIR="/var/lib/jenkins/jobs"
JENKINS_TMPDIR="/tmp/jenkins-backup"
JENKINS_BACKUP_DIR="/var/backups/jenkins"

# Check if jobs already exists
if [ "$(ls -A JENKINS_$CHKDIR)" ]; then
	echo "Jenkins backups already exist. No data restored"
else

	if [ "$(ls -A $JENKINS_BACKUP_DIR)" ]; then
		# Restore backups to temp dir
		duply jenkins restore $JENKINS_TMPDIR

		if [ "$(ls -A $JENKINS_TMPDIR)" ]; then
			# Stop Jenkins
			service jenkins stop

			rm -rf /var/lib/jenkins
			mv $JENKINS_TMPDIR $JENKINS_DIR

			# Restart Jenkins
			service jenkins start
		fi
	else
		echo "No Jenkins backups available. No data restored"
	fi
fi
